bases:
  - ../environments/release_environment.yaml
---
bases:
  - ../gotmpl/helmfile.gotmpl
---
bases:
  - ../templates/release_template.yaml
---

helmDefaults:
  kubeContext: "Docker-Desktop"

release:
  - name: kube-boot
    chart: ./kube-boot
    inherit:
      - template: release
