bases:
  - ../environments/release_environment.yaml
---
bases:
  - ../templates/release_template.yaml
---

helmDefaults:
  kubeContext: "docker-desktop"

releases:
  - name: kube-boot
    chart: ./kube-boot
    inherit:
      - template: release
