{{- if .Values.certManager.dns01.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.name }}
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: {{ .Values.certManager.server }}
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretRef }}
    solvers:
      - selector:
          dnsZones:
            {{ .Values.certManager.dns01.dnsZones }}
        dns01:
          {{- if eq .Values.certManager.dns01.provider "route53" }}
          route53:
            region: {{ .Values.certManager.dns01.region }}
            hostedZoneID: {{ .Values.certManager.dns01.hostedZoneId }}
          {{- else }}
            {{- fail "Unsupported DNS provider specified in values.yaml. supported provider are: route53" }}
          {{- end }}
{{- end }}