{{- if .Values.certManager.http01.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.name }}
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: {{ .Values.certManager.server }}
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretRef }}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.certManager.http01.ingressClassName }}
{{- end }}