# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-boot.fullname" . }}
  labels:
    {{- include "kube-boot.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.properties | nindent 4 }}