---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-{{ include "kube-boot.fullname" . }}
  labels:
    {{- include "kube-boot.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecrets | nindent 4 }}
  template:
    metadata:
      creationTimestamp: null
      name: sealed-{{ include "kube-boot.fullname" . }}
