apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-boot.fullname" . }}
  labels:
    {{- include "kube-boot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}