apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
  {{- include "spring-boot-microservice.labels" . | nindent 4 }}
  {{- if .Values.secret.labels }}
  {{- toYaml .Values.secret.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.secret.application }}
  application.yaml: >-
    {{- tpl . $ | b64enc | quote | nindent 4 }}
  {{- end }}
